Repository CMI-OSS/cbnu-alrami-app, pull requests merged in 2022-08, with the labels that each got.

#5 [App] webview 충림이 ui 가져오기
  App.tsx
  ios/Podfile.lock
  package.json
Labels: ⚙️ Setting

#9 [app] uuid 관련 로직
  App.tsx
  package.json
  yarn.lock
Labels: 📱 Mobile, ✨ Feature, android

#14 [app] flutter <-> webview 양방향 통신
  lib/src/controller/notification_controller.dart
  lib/src/page/cbnu_alrami.dart
Labels: ✨ Feature, android

#19 [ios] ios 스플래시 이미지 설정
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Group 518.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Group 518@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Group 518@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
Labels: ios

#16 [app] android gps 정보 허가하기
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  lib/src/controller/notification_controller.dart
  lib/src/page/cbnu_alrami.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature, android

#23 클립보드 복사 코드 추가
  lib/src/page/cbnu_alrami.dart
Labels: android

#26 뒤로가기 구현
  lib/src/page/cbnu_alrami.dart
Labels: ✨ Feature, android
