Repository CMI-OSS/cbnu-alrami-app, pull requests merged in 2023-03, with the labels that each got.

#42 [issue#41] 공지사항 상세페이지 app url 변경
  lib/main.dart
  lib/src/controller/notification_controller.dart
  pubspec.lock
Labels: 📱 Mobile, ♻︎ Refactor, android

#46 [app] 도메인 변경
  lib/main.dart
  lib/src/controller/notification_controller.dart
  lib/src/page/cbnu_alrami.dart
Labels: 📱 Mobile, ios, android

#45 ReadMe 작성 및 web 주소 변경
  README.md
  ios/Flutter/AppFrameworkInfo.plist
  ios/Flutter/Release.xcconfig
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
Labels: 📖 Docs, ios
